import "./globals.css";
import { Providers } from "./(auth)/provider";

import { Analytics } from "@vercel/analytics/react";
import DisabledNavbar from "./components/Disabled/DisabledNavbar";
import DisabledFooter from "./components/Disabled/DisableFooter";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Bukan BlogSpot !",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Share+Tech&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>
          <DisabledNavbar />
          {children}
          <Toaster />
          <Analytics />
          <DisabledFooter />
        </Providers>
      </body>
    </html>
  );
}
