import "./globals.css";
import { Providers } from "./(auth)/provider";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";

export const metadata = {
	title: "Bukan BlogSpot !",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='true'
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Archivo+Black&family=Share+Tech&display=swap'
					rel='stylesheet'
				/>
			</head>
			<body>
				<Providers>
					<Navbar />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
